//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_5_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryDetail
    {
        public int GalleryDetail_Id { get; set; }
        public string ImageSrc { get; set; }
        public string ImageTitle { get; set; }
        public int GalleryHeaderGalleryHeader_Id { get; set; }
    
        public virtual GalleryHeader GalleryHeader { get; set; }
    }
}
