//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_5_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryHeader
    {
        public GalleryHeader()
        {
            this.GalleryDetail = new HashSet<GalleryDetail>();
        }
    
        public int GalleryHeader_Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<GalleryDetail> GalleryDetail { get; set; }
    }
}
